apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      volumes: # Define volume
        - name: shared-image
          emptyDir: {}
      containers:
        - name: writer
          image: k13lucien/writer
          volumeMounts: # Mount volume
            - name: shared-image
              mountPath: /usr/src/app
        - name: reader
          image: k13lucien/reader
          volumeMounts: # Mount volume
            - name: shared-image
              mountPath: /usr/src/app