apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: random-string-svc
spec:
  type: ClusterIP
  selector:
    app: images
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8080
