apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pingpong-cpu-check
  namespace: exercises
spec:
  args:
    - name: namespace
      value: exercises
  metrics:
    - name: cpu-usage-rate
      interval: 30s
      count: 10
      failureLimit: 1
      successCondition: result[0] < 0.5
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local
          query: |
            sum(rate(container_cpu_usage_seconds_total{namespace="{{args.namespace}}"}[5m]))
