apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
spec:
  selector:
    app: pingpong
  type: ClusterIP
  ports:
    - name: status
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: pingpong
      port: 8081
      protocol: TCP
      targetPort: 8081
