apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: todo-config
data:
  BACKEND_URL: "http://todo-backend-svc:2345/todos"
  IMAGE_URL: "https://picsum.photos/1200"
  CACHE_DURATION: "600000"