apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: todo-generator
spec:
  schedule: "0 * * * *"  # every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-generator
              image: curlimages/curl:latest
              env:
                - name: TODO_BACKEND_URL
                  value: "http://todo-backend-svc:2345/todos"
              command:
                - /bin/sh
                - -c
                - |
                  # Get random Wikipedia article URL
                  RANDOM_URL=$(curl -Ls -o /dev/null -w %{url_effective} https://en.wikipedia.org/wiki/Special:Random)
                  echo "Random article: $RANDOM_URL"
                  
                  # Create Todo JSON
                  TODO_JSON="{\"text\":\"Read $RANDOM_URL\"}"
                  
                  # POST to backend
                  curl -s -X POST -H "Content-Type: application/json" -d "$TODO_JSON" $TODO_BACKEND_URL
          restartPolicy: OnFailure
